- vasp_files: [Al.poscar]
  x_scalings: [5]
  y_scalings: [10]
  z_scalings: [5]
  custom_fracture: false
  fracture: [[0, 1], [0, 0.5], [0.4, 0.6]]
  temps: [300]
  stress_plane: "010"
  iterations: 1000
  t_interval: 5

