- vasp_files: [Al.poscar, Al2O3.poscar]
  x_scalings: [6]
  y_scalings: [6]
  z_scalings: [6]
  custom_fracture: false
  fracture: [[0.4, 0.6], [0.4, 0.6], [0.4, 0.6]]
  temps: [300]
  stress_plane: "100"
  t_interval: 5
  iterations: 1000
