- vasp_files: [Al.poscar]
  x_scalings: [20]
  y_scalings: [20]
  z_scalings: [20]
  custom_fracture: false
  fracture: [[0, 1], [0, 0.5], [0.48, 0.52]]
  temps: [300]
  stress_plane: "100"
  potential: "EAM_Dynamo_FarkasCaro_2020_FeNiCrCoAl__MO_820335782779_000"
  strain_rate: 0.002
  relaxation_iterations: 500
  strain_interval: 10
  t_interval: 5
  iterations: 2000
