- vasp_files: [Al.poscar]
  x_scalings: [3]
  y_scalings: [3]
  z_scalings: [3]
  custom_fracture: false
  fracture: [[0, 1], [0, 0.5], [0.48, 0.52]]
  temps: [300]
  stress_plane: "010"
  iterations: 1000
  t_interval: 5