- vasp_files: [SiC.poscar]
  x_scalings: [2, 2, 2]
  y_scalings: [2, 2, 2]
  z_scalings: [2, 2, 2]
  custom_fracture: false
  fracture: [[0, 1], [0, 0.5], [0.4, 0.6]]
  temps: [0, 300, 20]
  stress_plane: "100"
  t_interval: 5
  iterations: 1000
