- vasp_files: [Ti.poscar]
  x_scalings: [10]
  y_scalings: [10]
  z_scalings: [10]
  custom_fracture: false
  fracture: [[0, 1], [0, 0.5], [0.48, 0.52]]
  temps: [300]
  stress_plane: "100"
  potential: "EAM_Dynamo_Ackland_1992_Ti__MO_748534961139_005"
  strain_rate: 0.01
  relaxation_iterations: 100
  strain_interval: 10
  t_interval: 5
  iterations: 200
