- vasp_files: [Ti.poscar]
  x_scalings: [20]
  y_scalings: [20]
  z_scalings: [20]
  custom_fracture: false
  fracture: [[0, 1], [0, 0.5], [0.48, 0.52]]
  temps: [300]
  stress_plane: "100"
  potential: "EAM_Dynamo_Ackland_1992_Ti__MO_748534961139_005"
  strain_rate: 0.002
  relaxation_iterations: 500
  strain_interval: 10
  t_interval: 5
  iterations: 2000
  allocated_time: "01:00:00"
- vasp_files: [C.poscar]
  x_scalings: [20]
  y_scalings: [20]
  z_scalings: [20]
  custom_fracture: false
  fracture: [[0, 1], [0, 0.5], [0.48, 0.52]]
  temps: [300]
  stress_plane: "100"
  potential: "Sim_LAMMPS_LCBOP_LosFasolino_2003_C__SM_469631949122_000"
  strain_rate: 0.002
  relaxation_iterations: 500
  strain_interval: 10
  t_interval: 5
  iterations: 2000
  allocated_time: "00:15:00"
